CREATE TABLE `audit_logging` (
  `Audit_Log_ID` int NOT NULL AUTO_INCREMENT,
  `User_ID` int NOT NULL,
  `Admin_ID` int NOT NULL,
  `Event_Time` datetime DEFAULT CURRENT_TIMESTAMP,
  `User_name` varchar(1000) NOT NULL,
  `Client_Host` varchar(1000) NOT NULL,
  `Db_Name` varchar(1000) NOT NULL,
  `Table_Name` varchar(1000) NOT NULL,
  `Operation` enum('INSERT','UPDATE','DELETE','OTHER') NOT NULL,
  `Sql_Statement` varchar(1000) NOT NULL,
  `Status` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Affected_Rows` int NOT NULL,
  `Remarks` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Old_Data` json DEFAULT NULL,
  `New_Data` json DEFAULT NULL,
  `Created_At` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Audit_Log_ID`),
  KEY `audit_logging_ibfk_1` (`User_ID`),
  KEY `audit_logging_ibfk_2` (`Admin_ID`),
  CONSTRAINT `audit_logging_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS` (`User_ID`),
  CONSTRAINT `audit_logging_ibfk_2` FOREIGN KEY (`Admin_ID`) REFERENCES `ADMIN_RECORDS` (`Admin_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
