CREATE TABLE `BOOKINGS` (
  `Booking_ID` int NOT NULL AUTO_INCREMENT,
  `User_ID` int DEFAULT NULL,
  `Spot_ID` int DEFAULT NULL,
  `Time_Slot_ID` int DEFAULT NULL,
  `Group_Size` int NOT NULL,
  `Reservation_Date` datetime(6) NOT NULL,
  `Visit_Date` datetime(6) NOT NULL,
  `Payment_ID` int DEFAULT NULL,
  `Status` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Created_At` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Booking_ID`),
  KEY `User_ID` (`User_ID`),
  KEY `Spot_ID` (`Spot_ID`),
  KEY `bookings_ibfk_3_idx` (`Payment_ID`),
  CONSTRAINT `bookings_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS` (`User_ID`),
  CONSTRAINT `bookings_ibfk_2` FOREIGN KEY (`Spot_ID`) REFERENCES `SPOTS_AVAILABILITY` (`Spot_ID`),
  CONSTRAINT `bookings_ibfk_3` FOREIGN KEY (`Payment_ID`) REFERENCES `PAYMENTS` (`Payment_ID`),
  CONSTRAINT `bookings_chk_1` CHECK (((`Group_Size` >= 2) and (`Group_Size` <= 5)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
