CREATE TABLE `daily_operational_log` (
  `Log_ID` int NOT NULL AUTO_INCREMENT,
  `Place_ID` int DEFAULT NULL,
  `Spot_ID` int DEFAULT NULL,
  `Time_Slot_ID` int DEFAULT NULL,
  `Log_Date` datetime(6) NOT NULL,
  `Visitor_Count` int NOT NULL,
  `Total_Sales` float NOT NULL,
  `Trash_Level` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Notes` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Created_At` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Log_ID`),
  KEY `Place_ID` (`Place_ID`),
  KEY `Spot_ID` (`Spot_ID`),
  KEY `Time_Slot_ID` (`Time_Slot_ID`),
  CONSTRAINT `daily_operational_log_ibfk_1` FOREIGN KEY (`Place_ID`) REFERENCES `PUBLIC_PLACES` (`Place_ID`),
  CONSTRAINT `daily_operational_log_ibfk_2` FOREIGN KEY (`Spot_ID`) REFERENCES `SPOTS_AVAILABILITY` (`Spot_ID`),
  CONSTRAINT `daily_operational_log_ibfk_3` FOREIGN KEY (`Time_Slot_ID`) REFERENCES `TIME_SLOTS` (`Time_Slot_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
